### ISSUE TITLE
Trouble using Github actions

### ISSUE THREAD

**Issue by dantheman0124** [CISC-CMPE-327/Information#14]
Is there any way I can get clarification on how to setup Github actions? The instructions page is unclear and I have no idea what to do. What do I need to do to set it up? This is for Assignment 0 and I am having trouble completing all the steps because of this.

**Comment by leordsong** [comment]
Which step blocked you?

**Comment by dantheman0124** [comment]
The step about continuous integration, with the various yml files. I am unsure what to do with those.

**Comment by leordsong** [comment]
Okay, GitHub actions are not required for A0. You and your group members just need to sign the contract by using pull request.

**Comment by steven-hh-ding** [comment]
Yes you don't need to setup the yaml file. It is provided in our template for either option. But we want you to understand what those mean that's why it is there.
