### ISSUE TITLE
A1 R6 (/buy) 

### ISSUE THREAD

**Issue by jolenelammers** [CISC-CMPE-327/Information#27]
![image](https://user-images.githubusercontent.com/31862367/95893645-f775b600-0d55-11eb-8d0a-3b75c5290dd9.png)

I believe that the first three cases covered by the fourth case, as if the ticket exists it should meet those requirements. And even if somehow the ticket exists and doesn't meet those requirements, shouldn't the user be able to buy any ticket that is there. 

Should we  still have tests  for these cases?

**Comment by steven-hh-ding** [comment]
first three: sanity check of the inputs before any further processing

just like in the login requirement, we still check whatever user input is valid or not, before further processing.

you can never trust user input. people can, for example, sql injection into the ticket name. so always check input, and always check all inputs.
