### ISSUE TITLE
A1: Problem with specifications for web app project

### ISSUE THREAD

**Issue by charasyn** [CISC-CMPE-327/Information#30]
Hello, I think I found a problem with the specifications we've been given.. According to R7, the /logout endpoint is only supposed to support the HTTP POST method. However, in the example testcases, the instructions state "Open /logout". Assuming that "opening" a page refers to navigating the web browser to that page, this will perform the HTTP GET method, which is unsupported by the /logout endpoint and should result in a 404 as per R8.

This is obviously not the intended behaviour. How should we deal with this discrepancy? I think maybe the specifications should be revised to allow /logout to use either GET or POST methods.

**Comment by steven-hh-ding** [comment]
YES! There is a discrepancy between the route table and the specification table.  Please create a pull request.
