### ISSUE TITLE
r6.6 The user has more balance than the ticket price * quantity + service fee (35%) + tax (5%)

### ISSUE THREAD

**Issue by jolenelammers** [CISC-CMPE-327/Information#43]
Would an insufficient funds error be processed in the backend, not the frontend? As from our understanding it relates to the core business logic, not the display / input validation. As it is listed as a requirement in the frontend, in this case will we have test cases for this in both the front end and the back end?

**Comment by steven-hh-ding** [comment]
Hello! For now let's just stay this way. So far we will just assume the backend is serving mostly the M part (model) and the business logics kindof mixing between the frontend and the backend (well they are just one program). If we follow the standard way, there is no much we can do for the frontend for such a small project :)
