### ISSUE TITLE
R4 potential missing specification

### ISSUE THREAD

**Issue by aubreymcleod** [CISC-CMPE-327/Information#46]
I just noticed that there is no constraint on the /sell route that prevents a user from listing an expired ticket. Given that R3.5 implies that no details will be shown for expired tickets, we may want to prevent users to adding expired tickets to the listings.

Additionally for R4.2, we may want to also define a minimum length for a ticket name.

**Comment by steven-hh-ding** [comment]
Yah you are right! Lets make the minimum of 6, and add the expiration limit. Could you create a pull request with a note of optional on the side? (since we past the requirement cut off point i.e. Thursday I can't make this mandatory to everyone).

**Comment by aubreymcleod** [comment]
> Yah you are right! Lets make the minimum of 6, and add the expiration limit. Could you create a pull request with a note of optional on the side? (since we past the requirement cut off point i.e. Thursday I can't make this mandatory to everyone).

Just for clarity's sake, are you asking me to push and pull a new branch to the course information page (I tried but I don't have permission to push a new branch there)?

**Comment by steven-hh-ding** [comment]
yah so you can fork this repository (upper right button, like make a copy but it is yours), make commits, then go to the pull requests page of this repo and create a pull request (from your forked one to this one). After the pull request, you will be added to the list of contributors.

**Comment by steven-hh-ding** [comment]
merged PR #49
