### ISSUE TITLE
Wrong image example on instruction_github_basic.md

### ISSUE THREAD

**Issue by Bool0s** [CISC-CMPE-327/Information#5]
The image example for "Add Education License 💗" is the same as the one on "Add Collaborators 🌊"
![image](https://user-images.githubusercontent.com/45517436/92499140-862c6b80-f1c9-11ea-8826-1d2dc4090d1b.png)

![image](https://user-images.githubusercontent.com/45517436/92499176-90e70080-f1c9-11ea-9883-e0acd8b9ace9.png)

:)

**Comment by steven-hh-ding** [comment]
fixed 🚀  could you verify? also need to add your name there for the contributors.

**Comment by Bool0s** [comment]
The images are indeed different now, but it seems as though the image for "Add Collaborators 🌊" is related to adding an education license and not the settings tab as described in the text. I'm not sure if this is intentional.

Also my name is Andrew Boulos.

**Comment by steven-hh-ding** [comment]
could you try refreshing? it is showing tabs here.. maybe not updated?

**Comment by Bool0s** [comment]
Ah yes it seems to be fixed now

**Comment by steven-hh-ding** [comment]
tagged your name there as well. thank you for letting me know.
