### ISSUE TITLE
A2 Assignment and Deadline

### ISSUE THREAD

**Issue by Slabrosse** [CISC-CMPE-327/Information#51]
Hello Professor Ding, 

I understand that the deadline posted for Assignment 2 is in 5 days for October 26th but the assignment itself hasn't been posted yet so I'm wondering if that is enough time to complete it? Additionally starting next week, it is fall reading week so I'm not sure what the university policy is around having assignments due during that period. A lot of students are travelling this weekend and it might be hard to coordinate a time to discuss and finish the assignment properly. Does that mean our quiz is next week too? Also, what would it be on because we haven't had any lectures posted in a while. 

Thanks!

**Comment by steven-hh-ding** [comment]
yah that gonna be the week after will update things tonight!

**Comment by steven-hh-ding** [comment]
Mini-exam 2 will be on systematic testing and black box testing only
