### ISSUE TITLE
Assignment 2 more QAs

### ISSUE THREAD

**Issue by lucidorangee** [CISC-CMPE-327/Information#65]
[questions for cisc327.docx](https://github.com/CISC-CMPE-327/Information/files/5502599/questions.for.cisc327.docx)

Hello! My name is Jihoo/Ryan, and I really wanted to make a quality test plan, but I did not understand many parts of the test plan requirements. 
I wanted to send this in a private email but I could not find your address, so I have posted this on discord as well as on here (this one is more organized).
Thank you in advance.

**Comment by Kymed** [comment]
"What do you mean by classes and methods" This was covered in 124
"How detailed should a description be?", "How clear is 'clarity' considered?" Yes they're subjective statements, just try your best.
"What does markdown format mean?" The guide to markdown files is the first link when you google 'Markdown format'.

Calm down a bit man haha, in software engineering positions you have to learn on the job all the time, and you're often faced with subjective evaluation. This document is a little much lol.

**Comment by Kymed** [comment]
Backend system crash course: https://developer.mozilla.org/en-US/docs/Learn/Server-side/First_steps/Introduction
Code review guide by palantir: https://medium.com/palantir/code-review-best-practices-19e02780015f
Virtual environments: https://docs.python.org/3/tutorial/venv.html
Deployed environments: https://developer.github.com/v3/repos/deployments/

**Comment by steven-hh-ding** [comment]
Alright, here you GO:

A design document in PDF or perferablly the markdown format for your project, giving the overall structure of your solution, showing the classes and methods as a diagram or table, with a brief (one sentence) description of the intention of each.

> What does markdown format mean? I’ve done a hand-made spreadsheet-like format in assignment 1 when creating testcasessummary.md – is that the format you would like this one to be in as well? Or would you prefer a list or an essay format? If so, are there specific checklists that we should follow so that we accidentally don’t mention something that we thought was obvious or not necessary? 

Yah that is markdown. It is up to you how to organize it. As long as we can tell that you covered all the required elements here. Also based on the diagram/table, we can tell the overall components/classes/methods. You can create it and have your teammate to review it and see if it is clear or not. 

> How detailed should the description be? Is there certain things that you want included, such as “make sure there’s always a diagram for each solution parts”?

Description is `brief (one sentence)`. As long as based on the diagram, you show that you address all the Rs (requirements) needed to be done for the assignment, it should be fine. Missing 1-2 function is okay. BUT in **reality**, documentation should cover everything. You saw something is not covered in others pull request, you can't merge them. 

> What do you mean by classes and methods? Apologies if it’s just due to my familiarity with javascript and web-development, but does “classes and methods” relate directly to the structure of the software? In that case, are you asking how we’ve made R1.1 work, R1.2 work, etc.,.?

Hmm like the `User` class  and the methods used for frontend routing. Yes they are related to the Requirements. e.g. the  `profile` method handles the user home page request etc.

**Comment by steven-hh-ding** [comment]
> What does “Detail code review” mean? Does it mean that each test review should have bunch of “fix here” “this is not right” from other group members? 

Yah you should review the other people's pull request and suggest changes. We did a walk-through with Leo in the live session. We don't expect you do review in very details for all pull requests but at least to see some interactions. But ideally all the pull requests should be approved/reviewed by someone like in A1. 

> If that’s the case, is it better for us to purposely not communicate as much and purposely create desyncs so that we have a lot to fix? Or is it better for us to not have anything to fix? Or are we only getting marked on the quality of comments that exist?

If you guys already fixed before the pull requests, make a note there on what have been done and assign the others that participate the fixes as reviewers. There is always something to fix. Especially when you become senior engineer, your job is to find typos and styling mistakes/inconsistency lol. 

For the mark, we want to see interactions that improve the quality. If there is a really bad code fragment does not follow specification with zero comments merged to the master at the almost the end of tag submission, and nobody give a shot (review/comment/approval), that will be the problem (means no one care about the quality).

**Comment by steven-hh-ding** [comment]
> How are "different levels" divided - examples given are frontend, backend, integration, but then doesn't integration not really do much?

Levels means testing level. Some tests are on only frontend (we did it by mocking), some tests can on only backend, and some can do both (the integration testing example that go through both backend and frontend)

> How does backend units work? Have we learned how backend programming works? 

Backend units? It is already there with examples working. Frontend/Backend doesn't mean that they have to be in different program. In our case, they are both linked into a single program (frontend.py import backend.py). 

> Are we uploading the files somewhere to deploy them as a website that anyone can access at any time? If so, what steps would we be taking to deploy them? Do we use github or other sources?

Deployment will be the last assignment (for web option). You will play with docker files and cloud deployment. Instruction will be given. 

> Do we need to specify and use database languages such as SQL and create a functioning backend with functioning data storage system in order to keep them working? How optimized should it be in terms of both performance and cost?

Backend comes with an example. We don't write SQL statement any more. All these things have been encapsulated and we only use data models (the User classes). We use sqlite so it means zero in performance and cost and zero optimization needed. 

> In that case, do we need to mention how it will be updated in the future and how it will be maintained? How long do we need it to be maintained? Is there specific vocabulary that you would like us to use for maintenance? Is there any hints to where we can look up these information?

For now you don't need to, but when you do your 499/498 you will learn to do it properly. If you want you can add those for sure. e.g. maintenance of the code base is done through git versioning system and CI pipeline. obsolete API and dependencies will be montiored by github dependabot (enabled by default) etc..

**Comment by steven-hh-ding** [comment]
> What is the price budget and consumer market that we should consider when deciding the order of the test cases? Or is there a specific priority that you would like as a customer? Or should I just put the order as most obvious to least obvious, or security issue priority? If we get to decide the order, are there examples of how we decide it so that priority isn’t based on opinions, or should it be based on opinions? 

So just do your imagination. No standard. But generally you started with development->unit testing->integration testing->system testing (for us sys testing is the same as integration testing as we only have two components). There was a slide show the cost of fixing a bug associated with the lifecycle of testing. Priority is given to small things first or things easily failed or things are critical. 

> Do you want us to list every test cases and explain why we gave each one a certain priority, or just the pattern that we’ve used?

Nope just cover the listed entries in the assignment instruction

**Comment by steven-hh-ding** [comment]
> When you say "techniques and tools used for testing", are you asking from the examples you gave from your slides, from researches and google, or just brief-ish description of our plan? (I'm afraid that I would do it one way, and it turns out that this isn't the format you were looking for or "correct", and I lose marks from misunderstanding.)

I think we mentioned this in another issue about the expectation. Pick whatever you think makes sense to you. We already have techniques (by default/design of the project assignments) e.g. requirement partitioning, mocking, front-end unit testing, regression testing (GitHub action is triggered whenever you updated the codebase). Again, expectation: make you aware of their existence. Standard answer: non-existed. 

> Are there some recommended techniques? I’ve tried to search this on google, but I am facing difficulties differentiating the techniques that are suitable for the given assignment, and I’m still unsure of the amount of consistency required.

Hmm maybe mini-exam 2 review there can give you a nice example.

> What does environments mean? Do we mention that we don't get to meet up? What does "cloud environment" mean - are we deploying our project on somewhere, like github website? Or are you talking about the github structure? Or is it simply the backend coding part?

There is a slide on environment. (basically any environments that you will run the testing) any one in the team running on windows? mac? linux? what browser (you don't have to change the default chrome)? The CI yaml file for github action bascially runs test in ubuntu. Actually you can add windows (but not required). Again, no standard answer. Your story your imagination. Expectation: awareness 

>. For responsibility, should we put you down as the manager of the project? Or are we considered the managers, aka, have the complete control over the project - if so, do we need to come up with a way to reward the client if a problem happens? Or do I simply write down "A is responsible if login page crashes and B is responsible if your ticket vanishes" etc.,.? If so, what happens if it's a collaborative effort? Do we just mention that we're all responsible?

Up to you! We don't reward users normally. We get paid instead lol. You reward white-hat hackers that find bugs in your program (bug bounty program). Again, not required. the second part you mentioned is good. Collaborative effort: the everyone. (but you still need someone to take action to fix it, rather than just say `contact tech support`)

**Comment by steven-hh-ding** [comment]
> What does budget management mean? "You have limited CI action minutes, how to monitor, keep track..."? How limited are we in terms of CI action minutes? Is there a specific way you would like us to monitor?

You can search how to check your CI time limit and how much it is gone through google. I think repo owner will be able to see it. No standard answer. You can assign someone to manually check maybe after each pull-request is merged. Up to you how to run your team.


> How "minimize" must I make the cost be? Because if I recall from one of the lecture slides, some tests are not necessary and are not "prioritized", meaning they aren't "necessary" necessarily, yet bugs might appear if they're not tested. Does that mean they're considered necessary or not?

E.g. oh shot we are low on the left CI minutes. Then do more local testing before pushing to the cloud. There are also other settings (not required) e.g. skip running CI when you just edit the markdown files (didn't update code anyway)

> Although I did it in assignment 1, I wasn't sure if I did it correctly - what I did was make sure everyone's branches were merged with master, than clicked on "tag" button beside and named it v1.0 - should I have named it something else, am I supposed to make tags through command line, was I supposed to make tags in each branches with different names, and is v1.0 approperiate name, or was there a specific name you would've preferred with tags for a specific reason that I did not understand? And does that apply equally to this assignment?

Don't worry. If any issues with the submission you will be contacted. Naming convention. No standard.. Different product may even has their own way. Most common one (php as example):
https://www.akeeba.com/how-do-version-numbers-work.html#:~:text=Reading%20version%20numbers&text=The%20leftmost%20number%20(1)%20is,%22%20or%20%22subminor%20version%22.
But you can do anything you want e.g. even A1 submission. A2 submission etc. In reality, it is a mixture of tags of versioning numbers and whatever product related concepts.

**Comment by steven-hh-ding** [comment]
>What does "number of pull-request reviews done by team_member_X" mean? Are we not supposed to do pull-request reviews of every pull-requests? Was there a specific number that we were supposed to review to simulate the cost of qa testing, or is that just to filter out who is doing their job and who isn't?

Every pull request is supposed to be checked and approved before merging. There is no specific number requirement. but we want to make sure pull request are not randomly merged (has to go through somebody like in A1). Team members are contributing to the project for both coding and reviews. 

> How clear is "clarity" considered? Is the amount of comments you've provided in 'frontend.py' enough for me to consider it an example, or do you need more details? I've had professors who had grades cut for having too little or too much comments with different standards, so I would appreciate an example of enough and clear comments if it is okay. Otherwise, some specifications on how specific my comments should be would be appreciated too.

So clarity means clear enough for someone else to understand. If you find existing comments enough to understand it means they are good. I don't think on the earth there is such a thing 'too much comments' on code. I have seen wonderful engineer's work that has two lines of code but 200 lines of comments. Consistency between the doc and the code is the key in reality.

There exists standards on code comments/stylings. But we don't have the time to add them in. 

> May I get more information on how the backend of this project works? I saw that you recommend pair programming for the assignment 2 (and I assume onwards) but I don't have too much experience with backends to understand if there's a standard protocol we follow for backend if we're given that "we're using python using flask" - is there specific libraries, languages, clouds that we use for the backend? What happens with data memory storage system and data management?

Backend is already in there. You don't have to separate frontend and backend into different programs. They are just logical partition of functionalities. They can be in different program or just in one program. Python+Flask is the frontend part (routing and HTML generation). Python+sqlalchemy is the backend part. But for now they are just in one program.

**Comment by lucidorangee** [comment]
I see... and one last question (sorry for adding on to already-long list)
Is it okay for me to put test plans under design document? Or did you want them seperate?

**Comment by steven-hh-ding** [comment]
@lucidorangee  any way you want just make sure  they are easy to find (not like in a nested 10 layers of folders)

**Comment by lucidorangee** [comment]
Thank you so much for the clarifications
